### Health Check
GET http://localhost:3000/health HTTP/1.1 

### Get all items
GET http://localhost:3000/items HTTP/1.1

### Get item by id
GET http://localhost:3000/items/1 HTTP/1.1

### Create item
POST http://localhost:3000/items HTTP/1.1
Content-Type: application/json

{
	"name": "Item 1"
}

### Delete item
DELETE http://localhost:3000/items/1 HTTP/1.1

### Update item
PUT http://localhost:3000/items/1 HTTP/1.1
Content-Type: application/json

{
	"name": "Item 1 (updated)"
}

