CREATE OR REPLACE TABLE bds (
		sid UUID DEFAULT generateUUIDv4(),
		sMa String NOT NULL,
		sNoiDung String NOT NULL,
		sTenTinh String NOT NULL,
		iID_MaTinh Int64 NOT NULL,
		sTenQuan String NOT NULL,
		iID_MaQuan Int64 NOT NULL,
		sTenPhuongXa String,
		iID_MaPhuongXa Int64,
		sTenDuong String NOT NULL,
		sLoaiHang String,
		iDienTich Decimal(6, 1),
		iSoTang Decimal(4, 1),
		iMatTien Decimal(4, 1),
		iGiaChaoHopDong Int64,
		sGiaChaoHopDong String,
		sHuongNha String,
		iID_HuongNha Int32,
		iSoPhongNgu Int32,
		iSoToilet Int32,
		sMoTa String NOT NULL,
		sFiles Array(String),
		sLat String,
		sLng String,
		sHotline FixedString(10),
		dNgayTao DateTime,
		createdAt DateTime DEFAULT now()
	) ENGINE = MergeTree PRIMARY KEY sid PARTITION BY toYYYYMM(createdAt);